farm/farm/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('acc/', include('main.urls')),
    path('', include('authentication.urls'))
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farm/main/urls.py
from django.urls import path
from . import views

app_name="farmers"

urlpatterns = [
  path("",views.login, name="login"),
  path("register/",views.register, name="register"),
  path("home/", views.index, name="home"),
  path("tasksPage/", views.tasksPage, name="tasksPage"),
  path("workersPage/", views.workersPage, name="workersPage"),
  path("createWorkersPage/", views.createWorkersPage, name="createWorkersPage"),
  path("createTasksPage/", views.createTasksPage, name="createTasksPage"),
  path("editTask/<id>",views.editTask),
  path("deleteTask/<id>",views.deleteTask),
  path("editWorker/<id>",views.editWorker),
  path("deleteWorker/<id>",views.deleteWorker),
  path("contact/",views.contact, name="contact"),
  path("workerHome/",views.workerHome, name="workerHome"),
  path("workerTask/",views.workerTask, name="workerTask"),
  path("workerWorkers/", views.workerWorkers, name="workerWorkers"),
  path("supervisorHome/", views.supervisorHome, name="supervisorHome"),
  path("supervisorCreateTaskPage/",views.supervisorCreateTaskPage,name="supervisorCreateTaskPage"),
  path("supervisorTaskPage/",views.supervisorTaskPage,name="supervisorTaskPage"),
  path("supervisorWorkerPage/",views.supervisorWorkerPage, name="supervisorWorkerPage"),
  path("supervisorCreateWorkerPage/",views.supervisorCreateWorkerPage, name="supervisorCreateWorkerPage"),
  path("SupervisorProfilePage/", views.SupervisorProfilePage, name="SupervisorProfilePage"),
  path("MainProfilePage/", views.MainProfilePage, name="MainProfilePage"),
  path("WorkerProfilePage/", views.WorkerProfilePage, name="WorkerProfilePage"),
  path("MainProfileForm/",views.MainProfileForm, name="MainProfileForm"),
  path("SupervisorProfileForm/",views.SupervisorProfileForm, name="SupervisorProfileForm"),
  path("WorkerProfileForm/",views.WorkerProfileForm, name="WorkerProfileForm"),
  path("chartPage/", views.chartPage, name="chartPage"),
  path("MaininventoryTablePage/", views.MaininventoryTablePage, name="MaininventoryTablePage"),
]

farm/main/models.py
from django.db import models
from authentication .models import CustomUser



# Create your models here.
class Farmer(models.Model):
    name=models.CharField( max_length=100)
    email=models.EmailField()
    username=models.CharField(max_length=100)
    password=models.CharField( max_length=50)
    phone=models.IntegerField()
    profession = models.CharField(max_length=100, null=True)
    image=models.ImageField( upload_to='images/')
    


class Task(models.Model):
    name=models.CharField(max_length=100)
    role=models.CharField( max_length=100)
    heading=models.CharField(max_length=100)
    description=models.CharField( max_length=100)
    days=models.IntegerField()
    
    def __str__(self):
        return self.name
    
    

class Worker(models.Model):
       name=models.CharField(max_length=100)
       email=models.EmailField()
       phone=models.IntegerField()
       worktype=models.CharField( max_length=100)
       role=models.CharField( max_length=100)
       status=models.CharField( max_length=100)
       image=models.ImageField(upload_to='workerimages/')
       
       
       
       def __str__(self):
           return self.name
       
class Contact(models.Model):
    name=models.CharField( max_length=100)
    email=models.EmailField()
    role=models.CharField( max_length=100)
    workId=models.IntegerField()
    subject=models.CharField( max_length=100)
    message=models.CharField( max_length=100)
    image=models.ImageField( upload_to='contactimages/')
    
    def __str__(self):
        return self.name
    
    
class SupervisorProfile(models.Model):
        name=models.CharField( max_length=100)
        email=models.EmailField(default='default@example.com')
        role=models.CharField( max_length=100)
        phone=models.IntegerField()
        image=models.ImageField(upload_to='profileimages/')
        
        def __str__(self):
            return self.name
        
        
        
class WorkerProfile(models.Model):
        name=models.CharField( max_length=100)
        email=models.EmailField(default='default@example.com')
        role=models.CharField( max_length=100)
        phone=models.IntegerField()
        image=models.ImageField(upload_to='profileimages/')
        
        def __str__(self):
            return self.name
        
    

class MainProfile(models.Model):
        name=models.CharField( max_length=100)
        email=models.EmailField()
        role=models.CharField( max_length=100)
        phone=models.IntegerField()
        image=models.ImageField(upload_to='profileimages/')
        
        def __str__(self):
            return self.name
        

class SupervisorCreateworker(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(default='default@example.com')
    phone=models.IntegerField()
    worktype=models.CharField( max_length=100)
    role=models.CharField( max_length=100)
    status=models.CharField( max_length=100)
    group=models.CharField( max_length=50)
    image=models.ImageField(upload_to='workerimages/')


def __str__(self):
    return self.name


class SupervisorCreatetask(models.Model):
    name=models.CharField(max_length=100)
    role=models.CharField( max_length=100)
    heading=models.CharField(max_length=100)
    description=models.CharField( max_length=100)
    days=models.IntegerField()
    
    def __str__(self):
        return self.name
    
    

farm/main/views.py
from django.shortcuts import render,redirect
from . models import Farmer, Task, Worker, SupervisorCreatetask, SupervisorCreateworker,WorkerProfile,SupervisorProfile,MainProfile
from django.views.decorators.csrf import csrf_exempt
from authentication.models import CustomUser

#Admins Pages
# Create your views here.
def dashboard(request):
    pass

def profile(request):
    pass

def tasks(request):
    pass

def workers(request):
    pass

def addworker(request):
    pass

def supervisors(request):
    pass

def addSupervisor(request):
    pass

def deleteWorker(request):
    pass

def deleteSupervisor(request):
    pass

def assignTask(request):
    pass

def deleteTask(request):
    pass

def worker(request):
    pass

def supervisor(request):
    pass

def task(request):
    pass














def login(request):
    return render(request,'login/login.html')

def register(request):
    return render(request,'login/register.html')

@csrf_exempt
def index(request):
    tasks=Task.objects.all()
    workers=Worker.objects.all()
    supervisorworkers=SupervisorCreateworker.objects.all()
    supervisortasks=SupervisorCreatetask.objects.all()
    mainProfiles=MainProfile.objects.all()
    context={
        'tasks': tasks,
        'workers':workers,
        'supervisorworkers': supervisorworkers,
        'supervisortasks': supervisortasks,
        'mainProfiles': mainProfiles
    }
    return render(request,'main/index.html',context)

def workersPage(request):
    workers=Worker.objects.all()
    supervisorworkers=SupervisorCreateworker.objects.all()
    context={
        'workers':workers,
        'supervisorworkers':supervisorworkers
    }
    return render(request,'main/workers-page.html',context)

def createWorkersPage(request):
    if request.method=="POST":
        name=request.POST['name']
        phone=request.POST['phone']
        role=request.POST['role']
        email=request.POST['email']
        worktype=request.POST['worktype']
        status=request.POST['status'].lower()
        image=request.FILES['image']
        
        worker=Worker(name=name, phone=phone, role=role, email=email, worktype=worktype,status=status,image=image)
        create_user  = CustomUser.objects.create_user(username=name, email=email, user_type=role.lower(), password=email)
        create_user.save()
        worker.save()
        
        return redirect('/workersPage/')
    
    return render(request,'main/create-workers.html')

def editWorker(request, id):
    if request.method=="POST":
        name=request.POST['name']
        phone=request.POST['phone']
        role=request.POST['role']
        email=request.POST['email']
        worktype=request.POST['worktype']
        status=request.POST['status'].lower()
        image=request.FILES['image']
        
        
        workers=Worker.objects.get(id=id)
        
        workers.name = name
        workers.phone = phone
        workers.role = role
        workers.email = email
        workers.worktype = worktype
        workers.status = status
        workers.image = image
        
        workers.save()
        return redirect('/workersPage/')
    
    workers=Worker.objects.get(id=id)
    return render(request, 'main/edit-worker.html',{'workers': workers})

def deleteWorker(request, id):
    workers=Worker.objects.get(id=id)
    workers.delete()
    return redirect('/workersPage/')

def createTasksPage(request):
    if request.method=="POST":
        name=request.POST['name']
        role=request.POST['role']
        heading=request.POST['heading']
        description=request.POST['description']
        days=request.POST['days']
        
        task=Task(name=name,role=role,heading=heading,description=description,days=days)
        task.save()
        return redirect('/tasksPage/')    
               
    return render(request,'main/create-tasks.html')

def tasksPage(request):
    tasks=Task.objects.all()
    return render(request,'main/tasks-page.html',{'tasks': tasks})

def editTask(request, id):
    if request.method=="POST":
        name = request.POST['name']
        role = request.POST['role']
        heading = request.POST['heading']
        description = request.POST['description']
        days = request.POST['days']

        tasks=Task.objects.get(id = id)

        tasks.name = name
        tasks.role = role
        tasks.heading = heading
        tasks.description = description
        tasks.days = days

        tasks.save()
        return redirect('/tasksPage/')
        
    tasks=Task.objects.get(id = id)
    return render(request, 'main/edit-task.html',{'tasks': tasks})

def deleteTask(request, id):
    tasks=Task.objects.get(id=id)
    tasks.delete()
    
    return redirect('/tasksPage/')
    
def contact(request):
    if request.method=="POST":
        name=request.POST['name']
        email=request.POST['email']
        role=request.POST['role']
        workId=request.POST['workId']
        subject=request.POST['subject']
        message=request.POST['message']
        image=request.POST['image']
        
        contact=Contact(name=name, email=email, role=role, workId=workId, subject=subject, message=message, image=image)
        contact.save()
    return render(request,'workers/contact.html')

#Workers pages
def workerHome(request):
    supervisorworker=SupervisorCreateworker.objects.all()
    supervisortask=SupervisorCreatetask.objects.all()
    workerProfiles=WorkerProfile.objects.all()
    context={
        'supervisorworker': supervisorworker,
        'supervisortask': supervisortask,
        'workerProfiles':workerProfiles
       
    }
    return render(request,'workers/worker-home.html',context)

def workerTask(request):
    tasks=Task.objects.all()
    return render(request,'workers/worker-task.html',{'tasks': tasks})

def workerWorkers(request):
    workers=Worker.objects.all()
    return render(request, 'workers/worker-workers.html',{'workers': workers})

def supervisorHome(request):
        supervisortask = SupervisorCreatetask.objects.all()
        supervisorworker = SupervisorCreateworker.objects.all()
        worker = Worker.objects.all()  
        supervisorProfiles=SupervisorProfile.objects.all()

        context = {
            'worker': worker,
            'supervisortask': supervisortask,
            'supervisorworker': supervisorworker,
            'supervisorProfiles':supervisorProfiles
            
        }
        return render(request, 'supervisor/home.html', context)

def supervisorCreateTaskPage(request):
    if request.method=="POST":
        name=request.POST['name']
        role=request.POST['role']
        heading=request.POST['heading']
        description=request.POST['description']
        days=request.POST['days']
      
        
        supervisortask=SupervisorCreatetask(name=name,role=role,heading=heading,description=description,days=days)
        supervisortask.save()
        return redirect('/supervisorTasksPage/')    
    
    return render(request,'supervisor/create-task.html')

def supervisorEditTaskPage(request,id):
    if request.method=="POST":
        name = request.POST['name']
        role = request.POST['role']
        heading = request.POST['heading']
        description = request.POST['description']
        days = request.POST['days']

        supervisortasks=SupervisorCreatetask.objects.get(id = id)

        supervisortasks.name = name
        supervisortasks.role = role
        supervisortasks.heading = heading
        supervisortasks.description = description
        supervisortasks.days = days

        supervisortasks.save()
        return redirect('/supervisorTasksPage/')
        
    supervisortasks=SupervisorCreatetask.objects.get(id = id)
    return render(request,'supervisor/edit-task.html')

def supervisorTaskDelete(request,id):
    supervisortasks=SupervisorCreatetask.objects.get(id = id)
    supervisortasks.delete()
    return redirect('/supervisorTaskPage/')

def supervisorTaskPage(request):
    supervisortask=SupervisorCreatetask.objects.all()
    return render(request, 'supervisor/task-page.html',{'supervisortask': supervisortask})

def supervisorCreateWorkerPage(request):
    if request.method=="POST":
        name=request.POST['name']
        phone=request.POST['phone']
        role=request.POST['role']
        email=request.POST['email']
        worktype=request.POST['worktype']
        status=request.POST['status'].lower()
        image=request.FILES['image']
        group=request.POST['group']
        
        supervisorworker=SupervisorCreateworker(name=name, phone=phone, role=role, email=email, worktype=worktype,status=status,group=group,image=image)
        create_user  = CustomUser.objects.create_user(username=name, email=email, user_type=role.lower(), password=email)
        create_user.save()
        supervisorworker.save()
        
        return redirect('/supervisorWorkerPage/')
    return render(request, 'supervisor/create-worker.html')

def supervisorWorkerPage(request):
    supervisorworker=SupervisorCreateworker.objects.all()
    return render(request,'supervisor/worker.html',{'supervisorworker': supervisorworker})

def chartPage(request):
    return render(request, 'charts-chartjs.html')

def MaininventoryTablePage(request):
    return render(request,'main/inventory-table.html')

def MainProfileForm(request):
    if request.method=="POST":
        name=request.POST['name']
        role=request.POST['role']
        email=request.POST['email']
        phone=request.POST['phone']
        image=request.FILES['image']


        mainProfile=MainProfile(name=name,role=role,email=email,phone=phone,image=image)
        mainProfile.save()
        return redirect('/home/') 
    return render(request,'main/profile-form.html')

def MainProfilePage(request):
    mainProfiles=MainProfile.objects.all()
    context={
        'mainProfiles': mainProfiles
    }
    return render(request,'main/profile.html',context)

def SupervisorProfileForm(request):
    if request.method=="POST":

farm/main/templates/tables-data.html
{% extends "admin/layout.html" %}


{% load static %}




{% block body %}

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Data Tables</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Tables</li>
          <li class="breadcrumb-item active">Data</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Datatables</h5>
              <p>Add lightweight datatables to your project with using the <a href="https://github.com/fiduswriter/Simple-DataTables" target="_blank">Simple DataTables</a> library. Just add <code>.datatable</code> class name to any table you wish to conver to a datatable. Check for <a href="https://fiduswriter.github.io/simple-datatables/demos/" target="_blank">more examples</a>.</p>

              <!-- Table with stripped rows -->
              <table class="table datatable">
                <thead>
                  <tr>
                    <th>
                      <b>N</b>ame
                    </th>
                    <th>Ext.</th>
                    <th>City</th>
                    <th data-type="date" data-format="YYYY/DD/MM">Start Date</th>
                    <th>Completion</th>
                  </tr>
                </thead>
                <tbody>

                  <tr>
                    <td>Unity Pugh</td>
                    <td>9958</td>
                    <td>Curicó</td>
                    <td>2005/02/11</td>
                    <td>37%</td>
                  </tr>
                
           
            
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->

  {% endblock  %}









  
  {% for supervisorProfile in supervisorProfiles %}
            
  <div class="card">
    <div class="card-body pt-3">
      <div class="tab-content pt-2">
        <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
          <img src="{% url "supervisorProfile.image.url" %}" width="40px" alt="Profile-image" class="rounded-circle">
            </div>
        <div class="tab-pane fade show active profile-overview" >
        

          <h5 class="card-title">Profile Details</h5>

          <div class="row">
            <div class="col-lg-3 col-md-4 label ">Full Name</div>
            <div class="col-lg-9 col-md-8">{{supervisorProfile.name}}</div>
          </div>
          <br/>
          <div class="row">
            <div class="col-lg-3 col-md-4 label">Job</div>
            <div class="col-lg-9 col-md-8">{{supervisorProfile.role}}r</div>
          </div>
          <br/>
          <div class="row">
            <div class="col-lg-3 col-md-4 label">Phone</div>
            <div class="col-lg-9 col-md-8">0{{supervisorProfile.phone}}</div>
          </div>
<br/>
          <div class="row">
            <div class="col-lg-3 col-md-4 label">Email</div>
            <div class="col-lg-9 col-md-8">{{supervisorProfile.email}}</div>
          </div>

       


        
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  {% else %}

<div class="card">
      <div class="card-body pt-3">
        <div class="tab-content pt-2">
          <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
            <img src="{% static 'assets/img/profile-img.jpg' %}" width="40px" alt="Profile-image" class="rounded-circle">
              </div>
          <div class="tab-pane fade show active profile-overview" >
          

            <h5 class="card-title">Profile Details</h5>

            <div class="row">
              <div class="col-lg-3 col-md-4 label ">Full Name</div>
              <div class="col-lg-9 col-md-8">Kevin Anderson</div>
            </div>
            <br/>
            <div class="row">
              <div class="col-lg-3 col-md-4 label">Job</div>
              <div class="col-lg-9 col-md-8">Web Designer</div>
            </div>
            <br/>
            <div class="row">
              <div class="col-lg-3 col-md-4 label">Phone</div>
              <div class="col-lg-9 col-md-8">(436) 486-3538 x29071</div>
            </div>
  <br/>
            <div class="row">
              <div class="col-lg-3 col-md-4 label">Email</div>
              <div class="col-lg-9 col-md-8">k.anderson@example.com</div>
            </div>

            <div>
              <a href="{% url "farmers:SupervisorProfileForm" %}" class="btn create-button">Update Profile</a>
            </div>
          
          </div>
        </div>
      </div>
    </div>



  {% endif %}

</div><!-- End Bordered Tabs -->







{% else %}
          
<div class="card">
              <div class="card-body pt-3">
                <div class="tab-content pt-2">
                  <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                    <img src="{% static 'assets/img/profile-img.jpg' %}" width="40px" alt="Profile-image" class="rounded-circle">
                      </div>
                  <div class="tab-pane fade show active profile-overview" >
                  
  
                    <h5 class="card-title">Profile Details</h5>
  
                    <div class="row">
                      <div class="col-lg-3 col-md-4 label ">Full Name</div>
                      <div class="col-lg-9 col-md-8">Kevin Anderson</div>
                    </div>
                    <br/>
                    <div class="row">
                      <div class="col-lg-3 col-md-4 label">Job</div>
                      <div class="col-lg-9 col-md-8">Web Designer</div>
                    </div>
                    <br/>
                    <div class="row">
                      <div class="col-lg-3 col-md-4 label">Phone</div>
                      <div class="col-lg-9 col-md-8">(436) 486-3538 x29071</div>
                    </div>
          <br/>
                    <div class="row">
                      <div class="col-lg-3 col-md-4 label">Email</div>
                      <div class="col-lg-9 col-md-8">k.anderson@example.com</div>
                    </div>
  
                    <div>
                      <a href="{% url "farmers:SupervisorProfileForm" %}" class="btn create-button">Update Profile</a>
                    </div>
                  
                  </div>
                </div>
              </div>
            </div>



          {% endif %} -->


          {% else %}
          
          <div class="card">
                        <div class="card-body pt-3">
                          <div class="tab-content pt-2">
                            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                              <img src="{% static 'assets/img/profile-img.jpg' %}" width="40px" alt="Profile-image" class="rounded-circle">
                                </div>
                            <div class="tab-pane fade show active profile-overview" >
                            
            
                              <h5 class="card-title">Profile Details</h5>
            
                              <div class="row">
                                <div class="col-lg-3 col-md-4 label ">Full Name</div>
                                <div class="col-lg-9 col-md-8">Kevin Anderson</div>
                              </div>
                              <br/>
                              <div class="row">
                                <div class="col-lg-3 col-md-4 label">Job</div>
                                <div class="col-lg-9 col-md-8">Web Designer</div>
                              </div>
                              <br/>
                              <div class="row">
                                <div class="col-lg-3 col-md-4 label">Phone</div>
                                <div class="col-lg-9 col-md-8">(436) 486-3538 x29071</div>
                              </div>
                    <br/>
                              <div class="row">
                                <div class="col-lg-3 col-md-4 label">Email</div>
                                <div class="col-lg-9 col-md-8">k.anderson@example.com</div>
                              </div>
            
                              <div>
                                <a href="{% url "farmers:MainProfileForm" %}" class="btn create-button">Update Profile</a>
                              </div>
                            
                            </div>
                          </div>
                        </div>
                      </div>
        
        
        
                    {% endif %}