farm/farm/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('acc/', include('main.urls')),
    path('', include('authentication.urls'))
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farm/main/urls.py
from django.urls import path
from . import views

app_name="farmers"

urlpatterns = [
  path("",views.login, name="login"),
  path("register/",views.register, name="register"),
  path("home/", views.index, name="home"),
  path("tasksPage/", views.tasksPage, name="tasksPage"),
  path("workersPage/", views.workersPage, name="workersPage"),
  path("createWorkersPage/", views.createWorkersPage, name="createWorkersPage"),
  path("createTasksPage/", views.createTasksPage, name="createTasksPage"),
  path("editTask/<id>",views.editTask),
  path("deleteTask/<id>",views.deleteTask),
  path("editWorker/<id>",views.editWorker),
  path("deleteWorker/<id>",views.deleteWorker),
  path("contact/",views.contact, name="contact"),
  path("workerHome/",views.workerHome, name="workerHome"),
  path("workerTask/",views.workerTask, name="workerTask"),
  path("workerWorkers/", views.workerWorkers, name="workerWorkers"),
  path("supervisorHome/", views.supervisorHome, name="supervisorHome"),
  path("supervisorCreateTaskPage/",views.supervisorCreateTaskPage,name="supervisorCreateTaskPage"),
  path("supervisorTaskPage/",views.supervisorTaskPage,name="supervisorTaskPage"),
  path("supervisorWorkerPage/",views.supervisorWorkerPage, name="supervisorWorkerPage"),
  path("supervisorCreateWorkerPage/",views.supervisorCreateWorkerPage, name="supervisorCreateWorkerPage"),
  path("SupervisorProfilePage/", views.SupervisorProfilePage, name="SupervisorProfilePage"),
  path("MainProfilePage/", views.MainProfilePage, name="MainProfilePage"),
  path("WorkerProfilePage/", views.WorkerProfilePage, name="WorkerProfilePage"),
  path("MainProfileForm/",views.MainProfileForm, name="MainProfileForm"),
  path("SupervisorProfileForm/",views.SupervisorProfileForm, name="SupervisorProfileForm"),
  path("WorkerProfileForm/",views.WorkerProfileForm, name="WorkerProfileForm"),
  path("chartPage/", views.chartPage, name="chartPage"),
  path("MaininventoryTablePage/", views.MaininventoryTablePage, name="MaininventoryTablePage"),
]

farm/main/models.py
from django.db import models
from authentication .models import CustomUser



# Create your models here.
class Farmer(models.Model):
    name=models.CharField( max_length=100)
    email=models.EmailField()
    username=models.CharField(max_length=100)
    password=models.CharField( max_length=50)
    phone=models.IntegerField()
    profession = models.CharField(max_length=100, null=True)
    image=models.ImageField( upload_to='images/')
    


class Task(models.Model):
    name=models.CharField(max_length=100)
    role=models.CharField( max_length=100)
    heading=models.CharField(max_length=100)
    description=models.CharField( max_length=100)
    days=models.IntegerField()
    
    def __str__(self):
        return self.name
    
    

class Worker(models.Model):
       name=models.CharField(max_length=100)
       email=models.EmailField()
       phone=models.IntegerField()
       worktype=models.CharField( max_length=100)
       role=models.CharField( max_length=100)
       status=models.CharField( max_length=100)
       image=models.ImageField(upload_to='workerimages/')
       
       
       
       def __str__(self):
           return self.name
       
class Contact(models.Model):
    name=models.CharField( max_length=100)
    email=models.EmailField()
    role=models.CharField( max_length=100)
    workId=models.IntegerField()
    subject=models.CharField( max_length=100)
    message=models.CharField( max_length=100)
    image=models.ImageField( upload_to='contactimages/')
    
    def __str__(self):
        return self.name
    
    
class SupervisorProfile(models.Model):
        name=models.CharField( max_length=100)
        email=models.EmailField(default='default@example.com')
        role=models.CharField( max_length=100)
        phone=models.IntegerField()
        image=models.ImageField(upload_to='profileimages/')
        
        def __str__(self):
            return self.name
        
        
        
class WorkerProfile(models.Model):
        name=models.CharField( max_length=100)
        email=models.EmailField(default='default@example.com')
        role=models.CharField( max_length=100)
        phone=models.IntegerField()
        image=models.ImageField(upload_to='profileimages/')
        
        def __str__(self):
            return self.name
        
    

class MainProfile(models.Model):
        name=models.CharField( max_length=100)
        email=models.EmailField()
        role=models.CharField( max_length=100)
        phone=models.IntegerField()
        image=models.ImageField(upload_to='profileimages/')
        
        def __str__(self):
            return self.name
        

class SupervisorCreateworker(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField(default='default@example.com')
    phone=models.IntegerField()
    worktype=models.CharField( max_length=100)
    role=models.CharField( max_length=100)
    status=models.CharField( max_length=100)
    group=models.CharField( max_length=50)
    image=models.ImageField(upload_to='workerimages/')


def __str__(self):
    return self.name


class SupervisorCreatetask(models.Model):
    name=models.CharField(max_length=100)
    role=models.CharField( max_length=100)
    heading=models.CharField(max_length=100)
    description=models.CharField( max_length=100)
    days=models.IntegerField()
    
    def __str__(self):
        return self.name
    
    

farm/main/views.py
from django.shortcuts import render,redirect
from . models import Farmer, Task, Worker, SupervisorCreatetask, SupervisorCreateworker,WorkerProfile,SupervisorProfile,MainProfile
from django.views.decorators.csrf import csrf_exempt
from authentication.models import CustomUser

#Admins Pages
# Create your views here.
def dashboard(request):
    pass

def profile(request):
    pass

def tasks(request):
    pass

def workers(request):
    pass

def addworker(request):
    pass

def supervisors(request):
    pass

def addSupervisor(request):
    pass

def deleteWorker(request):
    pass

def deleteSupervisor(request):
    pass

def assignTask(request):
    pass

def deleteTask(request):
    pass

def worker(request):
    pass

def supervisor(request):
    pass

def task(request):
    pass














def login(request):
    return render(request,'login/login.html')

def register(request):
    return render(request,'login/register.html')

@csrf_exempt
def index(request):
    tasks=Task.objects.all()
    workers=Worker.objects.all()
    supervisorworkers=SupervisorCreateworker.objects.all()
    supervisortasks=SupervisorCreatetask.objects.all()
    mainProfiles=MainProfile.objects.all()
    context={
        'tasks': tasks,
        'workers':workers,
        'supervisorworkers': supervisorworkers,
        'supervisortasks': supervisortasks,
        'mainProfiles': mainProfiles
    }
    return render(request,'main/index.html',context)

def workersPage(request):
    workers=Worker.objects.all()
    supervisorworkers=SupervisorCreateworker.objects.all()
    context={
        'workers':workers,
        'supervisorworkers':supervisorworkers
    }
    return render(request,'main/workers-page.html',context)

def createWorkersPage(request):
    if request.method=="POST":
        name=request.POST['name']
        phone=request.POST['phone']
        role=request.POST['role']
        email=request.POST['email']
        worktype=request.POST['worktype']
        status=request.POST['status'].lower()
        image=request.FILES['image']
        
        worker=Worker(name=name, phone=phone, role=role, email=email, worktype=worktype,status=status,image=image)
        create_user  = CustomUser.objects.create_user(username=name, email=email, user_type=role.lower(), password=email)
        create_user.save()
        worker.save()
        
        return redirect('/workersPage/')
    
    return render(request,'main/create-workers.html')

def editWorker(request, id):
    if request.method=="POST":
        name=request.POST['name']
        phone=request.POST['phone']
        role=request.POST['role']
        email=request.POST['email']
        worktype=request.POST['worktype']
        status=request.POST['status'].lower()
        image=request.FILES['image']
        
        
        workers=Worker.objects.get(id=id)
        
        workers.name = name
        workers.phone = phone
        workers.role = role
        workers.email = email
        workers.worktype = worktype
        workers.status = status
        workers.image = image
        
        workers.save()
        return redirect('/workersPage/')
    
    workers=Worker.objects.get(id=id)
    return render(request, 'main/edit-worker.html',{'workers': workers})

def deleteWorker(request, id):
    workers=Worker.objects.get(id=id)
    workers.delete()
    return redirect('/workersPage/')

def createTasksPage(request):
    if request.method=="POST":
        name=request.POST['name']
        role=request.POST['role']
        heading=request.POST['heading']
        description=request.POST['description']
        days=request.POST['days']
        
        task=Task(name=name,role=role,heading=heading,description=description,days=days)
        task.save()
        return redirect('/tasksPage/')    
               
    return render(request,'main/create-tasks.html')

def tasksPage(request):
    tasks=Task.objects.all()
    return render(request,'main/tasks-page.html',{'tasks': tasks})

def editTask(request, id):
    if request.method=="POST":
        name = request.POST['name']
        role = request.POST['role']
        heading = request.POST['heading']
        description = request.POST['description']
        days = request.POST['days']

        tasks=Task.objects.get(id = id)

        tasks.name = name
        tasks.role = role
        tasks.heading = heading
        tasks.description = description
        tasks.days = days

        tasks.save()
        return redirect('/tasksPage/')
        
    tasks=Task.objects.get(id = id)
    return render(request, 'main/edit-task.html',{'tasks': tasks})

def deleteTask(request, id):
    tasks=Task.objects.get(id=id)
    tasks.delete()
    
    return redirect('/tasksPage/')
    
def contact(request):
    if request.method=="POST":
        name=request.POST['name']
        email=request.POST['email']
        role=request.POST['role']
        workId=request.POST['workId']
        subject=request.POST['subject']
        message=request.POST['message']
        image=request.POST['image']
        
        contact=Contact(name=name, email=email, role=role, workId=workId, subject=subject, message=message, image=image)
        contact.save()
    return render(request,'workers/contact.html')

#Workers pages
def workerHome(request):
    supervisorworker=SupervisorCreateworker.objects.all()
    supervisortask=SupervisorCreatetask.objects.all()
    workerProfiles=WorkerProfile.objects.all()
    context={
        'supervisorworker': supervisorworker,
        'supervisortask': supervisortask,
        'workerProfiles':workerProfiles
       
    }
    return render(request,'workers/worker-home.html',context)

def workerTask(request):
    tasks=Task.objects.all()
    return render(request,'workers/worker-task.html',{'tasks': tasks})

def workerWorkers(request):
    workers=Worker.objects.all()
    return render(request, 'workers/worker-workers.html',{'workers': workers})

def supervisorHome(request):
        supervisortask = SupervisorCreatetask.objects.all()
        supervisorworker = SupervisorCreateworker.objects.all()
        worker = Worker.objects.all()  
        supervisorProfiles=SupervisorProfile.objects.all()

        context = {
            'worker': worker,
            'supervisortask': supervisortask,
            'supervisorworker': supervisorworker,
            'supervisorProfiles':supervisorProfiles
            
        }
        return render(request, 'supervisor/home.html', context)

def supervisorCreateTaskPage(request):
    if request.method=="POST":
        name=request.POST['name']
        role=request.POST['role']
        heading=request.POST['heading']
        description=request.POST['description']
        days=request.POST['days']
      
        
        supervisortask=SupervisorCreatetask(name=name,role=role,heading=heading,description=description,days=days)
        supervisortask.save()
        return redirect('/supervisorTasksPage/')    
    
    return render(request,'supervisor/create-task.html')

def supervisorEditTaskPage(request,id):
    if request.method=="POST":
        name = request.POST['name']
        role = request.POST['role']
        heading = request.POST['heading']
        description = request.POST['description']
        days = request.POST['days']

        supervisortasks=SupervisorCreatetask.objects.get(id = id)

        supervisortasks.name = name
        supervisortasks.role = role
        supervisortasks.heading = heading
        supervisortasks.description = description
        supervisortasks.days = days

        supervisortasks.save()
        return redirect('/supervisorTasksPage/')
        
    supervisortasks=SupervisorCreatetask.objects.get(id = id)
    return render(request,'supervisor/edit-task.html')

def supervisorTaskDelete(request,id):
    supervisortasks=SupervisorCreatetask.objects.get(id = id)
    supervisortasks.delete()
    return redirect('/supervisorTaskPage/')

def supervisorTaskPage(request):
    supervisortask=SupervisorCreatetask.objects.all()
    return render(request, 'supervisor/task-page.html',{'supervisortask': supervisortask})

def supervisorCreateWorkerPage(request):
    if request.method=="POST":
        name=request.POST['name']
        phone=request.POST['phone']
        role=request.POST['role']
        email=request.POST['email']
        worktype=request.POST['worktype']
        status=request.POST['status'].lower()
        image=request.FILES['image']
        group=request.POST['group']
        
        supervisorworker=SupervisorCreateworker(name=name, phone=phone, role=role, email=email, worktype=worktype,status=status,group=group,image=image)
        create_user  = CustomUser.objects.create_user(username=name, email=email, user_type=role.lower(), password=email)
        create_user.save()
        supervisorworker.save()
        
        return redirect('/supervisorWorkerPage/')
    return render(request, 'supervisor/create-worker.html')

def supervisorWorkerPage(request):
    supervisorworker=SupervisorCreateworker.objects.all()
    return render(request,'supervisor/worker.html',{'supervisorworker': supervisorworker})

def chartPage(request):
    return render(request, 'charts-chartjs.html')

def MaininventoryTablePage(request):
    return render(request,'main/inventory-table.html')

def MainProfileForm(request):
    if request.method=="POST":
        name=request.POST['name']
        role=request.POST['role']
        email=request.POST['email']
        phone=request.POST['phone']
        image=request.FILES['image']


        mainProfile=MainProfile(name=name,role=role,email=email,phone=phone,image=image)
        mainProfile.save()
        return redirect('/home/') 
    return render(request,'main/profile-form.html')

def MainProfilePage(request):
    mainProfiles=MainProfile.objects.all()
    context={
        'mainProfiles': mainProfiles
    }
    return render(request,'main/profile.html',context)

def SupervisorProfileForm(request):
    if request.method=="POST":

farm/main/templates/main/create-tasks.html
{% extends "main/layout.html" %}
{% load static %}


{% block body %}

  <main id="main" class="main">






    <div class="row gy-4">

    

      <div class="col-xl-10">
        <div class="card p-4">
          <form action="" method="post" class="" enctype="multipart/form-data">

            {% csrf_token %}
            <div class="row gy-4">

              <div class="col-md-6">
                <input type="text" name="name" class="form-control" placeholder="Name" required>
              </div>

              <div class="col-md-6 ">
                <input type="text" class="form-control" name="role" placeholder="Role" required>
              </div>

              <div class="col-md-6 ">
                <input type="text" class="form-control" name="heading" placeholder="Heading"required>
              </div>

              <div class="col-md-6">
                <input type="number" class="form-control" name="days" placeholder="e.g 1 ,2 " required>
              </div>

              <div class="col-md-12">
                <textarea class="form-control" name="description" rows="6" placeholder="Description" required></textarea>
              </div>


              <div class="col-md-12 text-center">
                <button type="submit"class="btn btn-success ">Save</button>
              </div>

            </div>
          </form>
        </div>

      </div>

    </div>





  </main><!-- End #main -->


{% endblock  %}

farm/main/templates/main/create-workers.html
{% extends "main/layout.html" %}
{% load static %}


{% block body %}

  <main id="main" class="main">

    <div class="row gy-4">

    

      <div class="col-xl-10">
        <div class="card p-4">
          <form action="" method="post" class="" enctype="multipart/form-data">

            {% csrf_token %}
            <div class="row gy-4">

              <div class="col-md-12">
                <input type="text" name="name" class="form-control" placeholder="Name" required>
              </div>

              <div class="col-md-6 ">
                <input type="email" class="form-control" name="email" placeholder="Email" required>
              </div>

              <div class="col-md-6 ">
                <input type="text" class="form-control" name="phone" placeholder="Phone number"required>
              </div>

              <div class="col-md-6 " >
                <input type="text" class="form-control" name="role" placeholder="Role" required>
              </div>

              <div class="col-md-6 ">
                <input type="text" class="form-control" name="group" placeholder="A, B, N/A" >
              </div>

              <div class="col-md-6">
                <input type="text" class="form-control" name="status" placeholder="e.g leave, terminated,active" required>
              </div>

              <div class="col-md-6">
                <input type="text" class="form-control" name="worktype" placeholder="e.g contract" required>
              </div>
              

              <div class="col-md-12 ">
                <input type="file" class="form-control" name="image" required>
              </div>

              <div class="col-md-12 text-center">
                <button type="submit"class="btn btn-success ">Submit</button>
              </div>

            </div>
          </form>
        </div>

      </div>

    </div>





  </main><!-- End #main -->


{% endblock  %}

farm/main/templates/main/layout.html
{% load static %}







<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dashboard - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/9861babfd0.js" crossorigin="anonymous"></script>
  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  


</head>

<body>




   <!-- ======= Sidebar ======= -->
   <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav dashboard-sidebar" id="sidebar-nav">



      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url "farmers:home" %}">
          <i class="fa-solid fa-house " style="color: #FFFFFF;"></i>
          <span>Home</span>
        </a>
      </li><!-- End Profile Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url "farmers:workersPage" %}">
          <i class="fa-solid fa-users" style="color: #FFFFFF;"></i>
          <span>Workers</span>
        </a>
      </li><!-- End Profile Page Nav -->

      



      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url "farmers:tasksPage" %}">
          <i class="fa-solid fa-business-time" style="color: #FFFFFF;"></i>
          <span>Tasks</span>
        </a>
      </li><!-- End Profile Page Nav -->
    
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url "farmers:MainProfilePage" %}">
          <i class="fa-solid fa-user" style="color: #FFFFFF;"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url "farmers:MaininventoryTablePage" %}">
          <i class="fa-solid fa-list" style="color: #FFFFFF;"></i>
          <span>Inventory</span>
        </a>
      </li><!-- End Profile Page Nav -->
    
  
   

   

     
      <div class="sidebar-footer">
     

   

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url "farmers:contact" %}">
          <i class="bi bi-envelope me-2"></i>
          <span>Contact</span>
        </a>
      </li><!-- End Contact Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url "farmers:login" %}">
          <i class="bi bi-card-list me-2"></i>
          <span>Log out</span>
        </a>
      </li><!-- End Register Page Nav -->

      <li class="nav-item ">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <img src="{% static 'assets/img/profile-img.jpg' %}" width="50px"alt="Profile" class="rounded-circle">
          <span class="d-none d-md-block  ps-2">K. Anderson</span>
        </a><!-- End Profile Iamge Icon -->
      </li><!-- End Login Page Nav -->

      <div>

    </ul>

  </aside><!-- End Sidebar-->




  

  {% block  body%}

  {% endblock  %}



<footer class=" text-center"><i class="fa-regular fa-sm  fa-copyright me-1"style="color: #3C5E13;"></i>2024 AgriGrow. All Rights Reserved.</footer>
  



<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
<script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
<script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

farm/main/templates/main/profile-form.html
{% extends "main/layout.html" %}
{% load static %}


{% block body %}

  <main id="main" class="main">






    <div class="row gy-4">

      <div class="col-xl-10">
        <div class="card p-4">
          <form action="" method="post" class="" enctype="multipart/form-data">

            {% csrf_token %}
            <div class="row gy-4">

              <div class="col-md-6">
                <input type="text" name="name" class="form-control" placeholder="Name" required>
              </div>

              <div class="col-md-6 ">
                <input type="text" class="form-control" name="role" placeholder="Role" required>
              </div>


              <div class="col-md-6">
                <input type="email" class="form-control" name="email" placeholder="joedoe@gmail.com " required>
              </div>

              <div class="col-md-6">
                <input type="number" class="form-control" name="phone" placeholder="e.g 07+++" required>
              </div>

              <div class="col-md-12">
                <input type="file" class="form-control" name="image" required>
              </div>
           

              <div class="col-md-12 text-center">
                <button type="submit"class="btn btn-success ">Save</button>
              </div>

            </div>
          </form>
        </div>

      </div>

    </div>





  </main><!-- End #main -->


{% endblock  %}

farm/main/templates/main/tasks-page.html
{% extends "main/layout.html" %}


{% load static %}



{% block  body%}


 

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Tasks Page</h1>
    </div><!-- End Page Title -->

    <div>
      <a href="{% url "farmers:createTasksPage" %}" class="btn create-button">Create task</a>
    </div>

    <section class="section">
      <div class="row">

        {% for task in tasks %}
        
      
        <div class="col-lg-12 task-card">
          <div class="card ">
            <div class="card-body">
              <h5 class="card-title"> {{task.name}}</h5>
              <span class="ms-2">{{task.role}}</span>
              <p class="ms-2 me-2">{{task.heading}}</p>
               <div class="tasks-align">
              <div>
              <span class="ms-2 me-2">{{task.description}}</span>
              </div>
                <div>
              <span class="ms-2 me-2">{{task.days}} days</span>
                </div>
              </div>

              <span>
                <a href="/editTask/{{task.id}}" class="btn create-button  ms-1 me-2">Edit task</a>
              </span>
              <span>
                <a href="/deleteTask/{{task.id}}" class="btn create-button">Delete task</a>
              </span>

            </div>
          </div>
        </div>
        {% endfor %}


      </div>
    </section>

  </main><!-- End #main -->

{% endblock  %}

farm/main/templates/main/workers-page.html
{% extends "main/layout.html" %}



{% load static %}


{% block  body%}

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Workers Details</h1>
    </div><!-- End Page Title -->

<div class="create-button-container">
  <a href="{% url "farmers:createWorkersPage" %}" class=" btn create-button ">Add worker</a>
</div>


    <section class="section">
      <div class="row align-items-top">
        <div class="col-lg-10">


          {% for worker in workers%}
          <div class="card  mb-3">
            <div class="row g-0">
         <div class="col-md-4 ">
                <img src="{{worker.image.url}}"class="img-fluid rounded mt-2 ms-2" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{{worker.name}}</h5><span>417100{{worker.id}}</span>
                  <p class="card-text">{{worker.role}}</p>
                  <p class="card-text">0{{worker.phone}}</p>
                  <p class="card-text">{{worker.worktype}}</p>
                  <p class="card-text">{{worker.email}}</p>
                  <p class="card-text">Employment status</p>
                  {% if  worker.status == "terminated" %}
                  <button type="button" class="btn btn-danger">Terminated</button>
                  {% elif worker.status == "active" %}
                  <button type="button" class="btn btn-success">Active</button>
                  {% elif worker.status == "leave"  %}
                  <button type="button" class="btn btn-warning">Leave</button>
                  {% else %}
                <p>Invalid entry!!</p>
                  {% endif %}
              <div>
                  <span>
                    <a href="/editWorker/{{worker.id}}" class="btn create-button ms-1 me-2">Edit worker</a>
                  </span>
                  <span>
                    <a href="/deleteWorker/{{worker.id}}" class="btn create-button">Delete worker</a>
                  </span>
                </div>
                </div>
              </div>
          
          
            </div>
          </div><!-- End Card with an image on left -->
          {% endfor %}
        

          {% for supervisorworker in supervisorworkers%}
          <div class="card  mb-3">
            <div class="row g-0">
         <div class="col-md-4 ">
                <img src="{{supervisorworker.image.url}}"class="img-fluid rounded mt-2 ms-2" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{{supervisorworker.name}}</h5><span>417100{{worker.id}}</span>
                  <p class="card-text">{{supervisorworker.role}}</p>
                  <p class="card-text">0{{supervisorworker.phone}}</p>
                  <p class="card-text">{{supervisorworker.worktype}}</p>
                  <p class="card-text">{{supervisorworker.email}}</p>
                  <p class="card-text">Employment status</p>
                  {% if  supervisorworker.status == "terminated" %}
                  <button type="button" class="btn btn-danger">Terminated</button>
                  {% elif supervisorworker.status == "active" %}
                  <button type="button" class="btn btn-success">Active</button>
                  {% elif supervisorworker.status == "leave"  %}
                  <button type="button" class="btn btn-warning">Leave</button>
                  {% else %}
                <p>Invalid entry!!</p>
                  {% endif %}
             
                </div>
              </div>
          
          
            </div>
          </div><!-- End Card with an image on left -->
          {% endfor %}


        </div>

      </div>
    </section>

  </main><!-- End #main -->

  

{% endblock  %}